# See this https://stackoverflow.com/a/71110028
name: nlq-notebooks
channels:
  - conda-forge
  # We want to have a reproducible setup, so we don't want default channels,
  # which may be different for different users. All required channels should
  # be listed explicitly here.
  - nodefaults
dependencies:
  - mamba=2.0.5
  - conda-lock=2.5.7
  - poetry=1.8.5
  - python=3.12.8
  - pip=24.3.1  # pip must be mentioned explicitly, or conda-lock will fail
