[tool.poetry]
name = "ttyg"
version = "0.0.1b0"
description = "Talk to your graph (TTYG) module provides functionality for Natural Language Querying (NLQ) using Graphwise GraphDB"
authors = []
readme = "README.md"
license = "Apache-2.0"

[tool.poetry.dependencies]
conda-lock = "2.5.7"
python = "3.12.9"
pip = "25.0.1"
jupyter = "1.1.1"
openai = "1.68.2"
sparqlwrapper = "2.0.0"
langgraph = "0.3.20"
langchain-openai = "0.3.10"

[tool.poetry.group.llm-databricks]
optional = true

[tool.poetry.group.llm-databricks.dependencies]
databricks-langchain = "0.4.0"

[tool.poetry.group.llm-anthropic]
optional = true

[tool.poetry.group.llm-anthropic.dependencies]
langchain-anthropic = "0.3.10"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
