[tool.poetry]
name = "ttyg"
version = "0.0.1b0"
description = "Talk to your graph (TTYG) module provides functionality for Natural Language Querying (NLQ) using Graphwise GraphDB"
authors = []
readme = "README.md"
license = "Apache-2.0"

[tool.poetry.dependencies]
conda-lock = "3.0.1"
python = "3.12.10"
pip = "25.1.1"
jupyter = "1.1.1"
sparqlwrapper = "2.0.0"
langgraph = "0.4.3"

[tool.poetry.group.test.dependencies]
pytest = "8.3.5"

[tool.poetry.group.llm-openai]
optional = true

[tool.poetry.group.llm-openai.dependencies]
langchain-openai = "0.3.16"

[tool.poetry.group.llm-databricks]
optional = true

[tool.poetry.group.llm-databricks.dependencies]
databricks-langchain = "0.4.2"

[tool.poetry.group.llm-anthropic]
optional = true

[tool.poetry.group.llm-anthropic.dependencies]
langchain-anthropic = "0.3.13"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
