[tool.poetry]
name = "nlq-notebooks"
version = "0.0.1a0"
description = "NLQ Notebooks"
authors = []
readme = "README.md"
license = "Apache-2.0"

[tool.poetry.dependencies]
conda-lock = "2.5.7"
python = "3.12.8"
pip = "24.3.1"
jupyter = "1.1.1"
openai = "1.59.7"
httpx = "0.27.2"
sparqlwrapper = "2.0.0"
langgraph = "0.2.62"
langchain-openai = "0.3.0"
databricks-langchain = "^0.3.0"
langchain-anthropic = "^0.3.7"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
